### ISSUE TITLE
ability to allow to override defaultErrorMessages

### ISSUE THREAD

**Issue by plentz** [CWSpear/angular-form-errors-directive#3]
something like this

``` html
<form-errors class="list-unstyled">
  <form-error-message required="we need this!"/>
  <form-error-message too-short="is shortish"/>
</form-errors>
```

**Comment by plentz** [comment]
this is specially useful for developers that use something like rails ou java to i18nize their apps, since you can do something like this:

``` rhtml
<form-errors>
  <form-error-message required="<%= t(:required) %>"/>
</form-errors>
```

**Comment by CWSpear** [comment]
There are a coulpes ways to override error messages.

You can [override the default messages](https://github.com/CWSpear/angular-form-errors-directive#overriding-and-extending-the-default-error-messages) (or extend it by adding more). This will change the default messages everywhere. 

You also have the option to override the message for each individual input: on each element there is a couple things you can do:

``` html
<input error-messages="{ required: 'we need this', minlength: 'is shortish' }" type="text" ng-model="username" name="username" required>
```

You can also just put a string there instead of an object and it will use that for all the error messages for that input.

From the source:

``` javascript
// set an errorMessage(s) to $errorMessages on the ngModel ctrl for later use
.directive('errorMessages', [function () {
    return {
        require: 'ngModel',
        link: function (scope, elem, attrs, ctrl) {
            // attrs.errorMessages can be:
            //    1) "must be filled out."
            //    2) "'must be filled out.'"
            //    3) "{ required: 'must be filled out.' }"
            // 1 & 2) will be the message for any kind of error
            // 3) allows you to specify each error (it will use the
            // defaultErrorMessages if you don't specify a specific error)
            try {
                ctrl.$errorMessages = scope.$eval(attrs.errorMessages);
            } catch (e) {
                ctrl.$errorMessages = attrs.errorMessages;
            }
        }
    };
}])
```

**Comment by CWSpear** [comment]
Yeah, for i18n, the global override is definitely the way to go. Slightly edited from the README docs (linked to in my last message):

``` javascript
app.config(function (FormErrorsOptionsProvider) {
    FormErrorsOptionsProvider.extendDefaultErrorMessages({ 
        // It only overrides what you pass it. All 
        // other default messages will be left alone
        required: 'é necessário.'
    });
})
```

**Comment by CWSpear** [comment]
What's nice about the `error-messages` object notation is that you can define that in the JavaScript and then just pass that variable to the directive (or you should be, I haven't tested in a while).

i.e.:

``` javascript
$scope.errorMessages = {
  required: 'é necessário.',
  minlength: 'é demasiado curto.',
  // etc, etc
};
```

In the template:

``` html
<input error-messages="errorMessages" type="text" ng-model="username" name="username" required ng-minlength="5">
```

**Comment by plentz** [comment]
yup, all the options you've mentioned I already know, my point is really that i18n the way I described is a lot easier, since it's not cool to put the `.config` block inside the template and creating a json from the i18n translations isn't quite nice as well(since if you use rails for example, you must have a way to get the keys you want and pass it to the directive).

using `error-menssages` solve this problem, but it create a small "unecessary" duplication.

**Comment by CWSpear** [comment]
The config doesn't go into the template? I don't understand. Why can't you define it there in your config?

What about putting an object on `<form-errors>` like using the `$scope.errorMessages` in my above example, what if you did this for _that_?

``` html
<form-errors error-messages="errorMessages"></form-errors>
```

and it updates the default error messages for just that directive?

**Comment by CWSpear** [comment]
I added what I described in `v1.4.0`. You can now override the default errors in each `<form-errors>`: [see docs](https://github.com/CWSpear/angular-form-errors-directive#overridingextending-default-error-messages-per-directive)

**Comment by plentz** [comment]
yup, that helps a lot :)
