### ISSUE TITLE
ability to use a template for displaying the errors

### ISSUE THREAD

**Issue by razvanz** [CWSpear/angular-form-errors-directive#4]
It would be nice the replace the `ul` template with a user defined one for displaying the errors. (`errors-template="myTmpl.html"`)

**Comment by CWSpear** [comment]
What kind of template would you use in this case that you can't do with the current markup and CSS?

**Comment by razvanz** [comment]
My main problem is that I would like to add error icons. Later on I might have to add other decorations.

**Comment by CWSpear** [comment]
You don't need to change the markup to do that. And it'd probably be better to just add one icon rather than an icon next to each error message, which would be ever easier to add.

I will take a look at your PR tho and consider it.

**Comment by razvanz** [comment]
By the way, I can see one fork on the repository that was only made to change the template. So, even though you won't consider my PR such a feature would be useful.

**Comment by CWSpear** [comment]
I said I _would_ consider it. It looks good, I just need some time to go through stuff and make sure it's not broken. Hopefully sometime this week.
