### ISSUE TITLE
character len mismatch

### ISSUE THREAD

**Issue by ghost** [CWSpear/angular-form-errors-directive#6]
when I put a single char in the first name field but it requires 5, there should be 4 "a" chars in "waaaay" so I know how many more to add.

**Comment by CWSpear** [comment]
I don't necessarily want to do this by default, but what if I gave access to the model value in the custom message definitions?

``` javascript
app.config(function (FormErrorsOptionsProvider) {
  FormErrorsOptionsProvider.extendDefaultErrorMessages({
    maxlength: 'is {{ model.length - maxlength }} character(s) too long.'
  });
});
```

``` html
<input name="message" maxlength="140" ng-model="tweet.message">
```

With the input **This input is more than 140 characters long. This input is more than 140 characters long. This input is more than 140 characters long.**, the message would then say:

> Message is 6 character(s) too long.

**Comment by CWSpear** [comment]
Closed as inactive.
