### ISSUE TITLE
Too many scopes?

### ISSUE THREAD

**Issue by ghost** [CWSpear/angular-form-errors-directive#7]
one scope per ng-model input? 

http://i.imgur.com/YE9u5ds.png

That seems unnecessary?

**Comment by CWSpear** [comment]
First of all: you tell me. Is that too many scopes? Why?

Second of all, the only scopes that this module adds that wouldn't already be there are in the `form-errors` directive itself (it creates an isolate scope). Everything else uses shared scope. If you remove this module, does it change the number of scopes created?

**Comment by ghost** [comment]
The angular js chrome addon that it's showing me the scopes in the debugger could be wrong, I am not sure. I dont know if it's too many scopes, but based on what a scope is, it doesn't seem correct. Unless I misunderstand the purpose of scope

If I remove the directive element "form-errors ng-show="showErrors" ng-cloak" (removed html tags because github filtered them in comments), the debugger no longer shows one scope per input. Even though I still have the module in my modules dependency injection array

**Comment by ghost** [comment]
This may be more helpful: http://i.imgur.com/lZinv40.png , it shows that I have an array of empty scopes, one for each input. When I comment out the directive element: http://i.imgur.com/CnuI2eO.png

**Comment by CWSpear** [comment]
Ok... so is this causing any issues?

**Comment by ghost** [comment]
Nope.. just wanted to bring it to the dev's attention

**Comment by CWSpear** [comment]
Ok. Thanks.
